const COLORS = {
   NO_SELECT : "#AAAAAA",
   PRIMARY_GREEN : "#00BB55",
   SECOND_GREEN: "#00B087",
   PRIMARY_DARK : "#0A0A0A",
   SECOND_DARK:"#222222",
   SUCCESS :"#00AFFF",
   SUCCESS_SECONDARY :"#16C",
   DANGER : "#FF5060",
   SECOND : "#FFFFFF",
   PURPLE_PRIMARY :"#845EC2",
   PRIMARY_RED:"#EE1E39"
 }

 export{
      COLORS
 }